"""The Scott-encoded Python AST, generated by reflection on ``ast``, round-trips real Python.

The compiler's target is a Python AST represented in the pure lambda-calculus by Scott encoding.
``encode`` reflects a real ``ast`` node into a Scott value; ``decode`` runs that value in the
interpreter and rebuilds the ``ast`` node generically with ``cls(*fields)``. A faithful encoding
means ``decode . encode`` is the identity on the AST, so the unparsed source round-trips, and the
decoded program runs.
"""

from __future__ import annotations

import ast

from co_lambda._dsl import build
from co_lambda._pyast import encode, roundtrip, to_python_source
from co_lambda._defun_runtime import recursion_headroom


def test_expressions_round_trip_faithfully() -> None:
    for source in (
        "v0 + 1",
        "lambda v0: v0 + 1",
        "(lambda v0: v0 + 1)(2)",
        "lambda x: lambda y: x + y",
        "f(1 + 2, x)",
        "x < 3",
    ):
        assert roundtrip(source, mode="eval") == ast.unparse(ast.parse(source, mode="eval"))


def test_module_with_a_loop_round_trips_and_runs() -> None:
    source = (
        "def f(n):\n"
        "    total = 0\n"
        "    while total < n:\n"
        "        total = total + 1\n"
        "    return total\n"
    )
    decoded = roundtrip(source, mode="exec")
    assert decoded == ast.unparse(ast.parse(source))
    namespace: dict = {}
    exec(decoded, namespace)
    assert namespace["f"](5) == 5


def test_scott_ast_decodes_and_executes() -> None:
    node = build(encode(ast.parse("(lambda v0: v0 + 1)(41)", mode="eval")))
    assert eval(to_python_source(node)) == 42


def test_call_by_need_statement_shape_round_trips() -> None:
    # The memoising-thunk shape the call-by-need target emits: def / nonlocal / if / assign / return /
    # 'is' comparison. The generic codec (with ast.Nonlocal and ast.Is in SUPPORTED) round-trips it, so
    # the call-by-need target can decode through _pyast.decode with no hand-written decoder.
    source = (
        "def _program():\n"
        "    v_0 = SENTINEL\n"
        "    def v_1():\n"
        "        nonlocal v_0\n"
        "        if v_0 is SENTINEL:\n"
        "            v_0 = v_2()\n"
        "        return v_0\n"
        "    return v_1\n"
        "program = _program()\n"
    )
    # Decode applies one handler per SUPPORTED constructor at each node, so a deeply nested module needs
    # more stack than CPython's default; the production decode path runs under the same headroom.
    with recursion_headroom():
        assert roundtrip(source, mode="exec") == ast.unparse(ast.parse(source))
