"""Generate the cyclic-stream code listing for the paper, rendered from the HOAS source terms.

The appendix lists the pure-lambda term ``r = Y (cons 0)`` and the small library it is built from: the
fixed-point combinator, the Scott list constructor, and the element. None of it is transcribed by hand;
each definition is the actual ``Builder`` from the source, rendered by ``co_lambda._hoas_latex`` with the
bound-variable names the Python lambdas carry and the other constants shown by name, so a definition reads
as itself and cross-references the rest. Each definition is a ``breqn`` ``dmath*``; the output is written to
``papers/co-lambda/generated/cyclic-zeros-code.tex`` and ``\\input`` by the paper.

``co-lambda-cyclic-zeros-code`` (``python -m co_lambda_examples._cyclic_zeros_code``) rewrites it.
"""

from __future__ import annotations

from pathlib import Path

from co_lambda._dsl import Builder
from co_lambda._hoas_latex import MATH_STYLE, render
from co_lambda._prelude import SCOTT_CONS, Y, ZERO

from co_lambda_examples._cyclic_zeros import STREAM_BUILDER
from co_lambda_examples._editdistance_code import _BREQN_STYLE

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "cyclic-zeros-code.tex"

# (group heading, ((name, builder), ...)). Order is dependency order: a definition uses only names above it.
_GROUPS: "tuple[tuple[str, tuple[tuple[str, Builder], ...]], ...]" = (
    ("fixed point", (("Y", Y),)),
    ("Scott list constructor", (("cons", SCOTT_CONS),)),
    ("the element", (("0", ZERO),)),
    ("the cyclic stream", (("r", STREAM_BUILDER),)),
)

_LATEX_HEADER = (
    "% Generated by co_lambda_examples._cyclic_zeros_code (co-lambda-cyclic-zeros-code). Do not edit;\n"
    "% regenerate with: python -m co_lambda_examples._cyclic_zeros_code\n"
)


def _names() -> "dict[int, str]":
    names: "dict[int, str]" = {}
    for _heading, definitions in _GROUPS:
        for name, builder in definitions:
            names.setdefault(id(builder), name)
    return names


def code_listing() -> str:
    """The committed LaTeX fragment: each definition a ``breqn`` ``dmath*``, rendered from its HOAS term."""
    names = _names()
    parts = [_LATEX_HEADER]
    for heading, definitions in _GROUPS:
        parts.append(f"\\smallskip\\noindent\\textit{{{heading}}}\\par\\nobreak")
        for name, builder in definitions:
            left = MATH_STYLE.constant(name)
            right = render(builder, names, _BREQN_STYLE)
            parts.append(f"\\begin{{dmath*}}\n{left} = {right}\n\\end{{dmath*}}")
    return "\n".join(parts) + "\n"


def main() -> None:
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(code_listing())
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
