"""Generate the precise term-level trace of the cyclic stream, read off the real interpreter.

The appendix carries the exact run; the body of Section~\\ref{sec:application} only narrates it. The trace
mirrors the pseudocode of Section~\\ref{sec:bridge}: ``Out`` on a state runs ``WHNF`` (the head-redex
contractions that unfold ``Y`` and expose the Scott cons cell), tables the state, and recurses into the
tail; the tail ``W·W`` is reached while it is still on the stack, so the solver closes a back edge. Every
step is produced by ``_cyclic_zeros.walk`` over the real interned terms, the exposed layers asserted equal
to ``weak_head_normalize``, never hand-written.

``co-lambda-cyclic-zeros-trace`` (``python -m co_lambda_examples._cyclic_zeros_trace``) rewrites the
committed ``papers/co-lambda/generated/cyclic-zeros-trace.tex``.
"""

from __future__ import annotations

from pathlib import Path

from co_lambda_examples._cyclic_zeros import StreamStep, walk

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "cyclic-zeros-trace.tex"


def render_trace(steps: "tuple[StreamStep, ...]") -> str:
    """The committed LaTeX fragment: the term-level walk as an indented ``lstlisting``."""
    header = (
        "% Generated by co_lambda_examples._cyclic_zeros_trace (co-lambda-cyclic-zeros-trace). Do not edit;\n"
        "% regenerate with: python -m co_lambda_examples._cyclic_zeros_trace\n"
    )
    body = "\n".join("  " * step.depth + step.text for step in steps)
    listing = "\\begin{lstlisting}[language=]\n" + body + "\n\\end{lstlisting}\n"
    return header + "\n" + listing


def main() -> None:
    steps, _states = walk()
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(render_trace(steps))
    print(f"wrote {_OUTPUT} ({len(steps)} lines)")


if __name__ == "__main__":
    main()
