"""Generate the cyclic-stream figure from the real interpreter.

The figure is the graph the solver returns for ``r = Y (cons 0)``, read off ``_cyclic_zeros.walk``: one
node per distinct state the solver tables (``r`` and the self-application ``W·W``), each carrying the head
``0`` the cons cell exposes, with a ``tail`` edge to the next state. ``r`` leads in; ``W·W``'s tail is
``W·W`` again, the back edge the solver closes when it re-enters that state on the stack, drawn as the
highlighted self-loop. The paper floats and captions the picture; this module owns only its body.

``co-lambda-cyclic-zeros-figure`` (``python -m co_lambda_examples._cyclic_zeros_figure``) rewrites the
committed ``papers/co-lambda/generated/cyclic-zeros-graph.tex``.
"""

from __future__ import annotations

from pathlib import Path

from co_lambda_examples._cyclic_zeros import StreamState, walk

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "cyclic-zeros-graph.tex"

_DX = 2.8


def _tex_name(name: str) -> str:
    return "$W\\,W$" if name == "W W" else f"${name}$"


def render_tikz(states: "tuple[StreamState, ...]") -> str:
    """The ``tikzpicture`` body: one node per state carrying its head value, ``tail`` edges between states,
    and the back edge as a highlighted self-loop on the state it re-enters."""
    assert states, "the stream exposes at least one state"
    assert any(state.tail_is_back_edge for state in states), "the cyclic stream must close a back edge"
    node = {state.name: f"s{index}" for index, state in enumerate(states)}
    cyclic = {state.tail_name for state in states if state.tail_is_back_edge}

    lines = [
        "% Generated by co_lambda_examples._cyclic_zeros_figure (co-lambda-cyclic-zeros-figure). Do not edit;",
        "% regenerate with: python -m co_lambda_examples._cyclic_zeros_figure",
        "% Nodes are the states the solver tables (read from the interpreter); each carries the head 0 the",
        "% cons cell exposes; the back edge is the tail re-entering a state still on the stack.",
        "\\begin{tikzpicture}[",
        "  font=\\footnotesize,",
        "  state/.style={draw, rounded corners, minimum width=9mm, minimum height=8mm, align=center, inner sep=1pt},",
        "  shared/.style={draw=red!65, fill=red!10, rounded corners, minimum width=9mm, minimum height=8mm, align=center, inner sep=1pt},",
        "  call/.style={-Stealth, gray!60, shorten >=1pt, shorten <=1pt},",
        "  back/.style={-Stealth, red!65, shorten >=1pt, shorten <=1pt},",
        "]",
    ]
    for index, state in enumerate(states):
        style = "shared" if state.name in cyclic else "state"
        lines.append(f"  \\node[{style}] ({node[state.name]}) at ({index * _DX:.2f},0) {{${state.head}$}};")
        lines.append(
            f"  \\node[font=\\footnotesize\\itshape, below=1.5pt of {node[state.name]}] {{{_tex_name(state.name)}}};"
        )
    for state in states:
        source, target = node[state.name], node[state.tail_name]
        if source == target:
            lines.append(
                f"  \\draw[back] ({source}) to[out=40,in=-40,looseness=8] node[right]{{\\itshape tail}} ({source});"
            )
        else:
            style = "back" if state.tail_is_back_edge else "call"
            lines.append(f"  \\draw[{style}] ({source}) -- node[above]{{\\itshape tail}} ({target});")

    caption_x = (len(states) - 1) * _DX / 2.0
    lines.append(
        f"  \\node[anchor=north, align=center] at ({caption_x:.2f},-1.2) "
        f"{{\\footnotesize each state exposes $\\mathtt{{cons}}\\;0\\;\\cdot$; unfolds to $0,0,0,\\ldots$}};"
    )
    lines.append("\\end{tikzpicture}")
    return "\n".join(lines) + "\n"


def main() -> None:
    _steps, states = walk()
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(render_tikz(states))
    print(f"wrote {_OUTPUT} ({len(states)} states)")


if __name__ == "__main__":
    main()
