"""Write the generated DEFUN compiler-example LaTeX fragment.

The console entry point ``co-lambda-defun-examples`` (see ``pyproject.toml``) runs ``main``;
equivalently ``python -m co_lambda_examples._examples``. The output is committed under
``papers/co-lambda/generated/`` and ``\\input`` by the paper; a test asserts the committed file matches
this builder, so regenerating after a compiler change is mandatory (and idempotent otherwise). Every
example runs the real DEFUN compiler: a term is ``defunctionalize`` of the term, the module of
``@interned`` closure classes it compiles to (one class per distinct source ``Lam``, each class's
``__call__`` the compiled beta reduction, applications emitted as ``Thunk`` nodes). The displayed
lambda is ``term_to_latex`` of the term (readable names).
"""

from __future__ import annotations

from pathlib import Path

from co_lambda._codec import church
from co_lambda._defunctionalize import defunctionalize
from co_lambda._dsl import Builder, build
from co_lambda._latex import term_to_latex
from co_lambda._prelude import IDENTITY, IS_ZERO, KESTREL, MULT, PLUS, SELF_APPLY, SUCC

# src/co_lambda_examples/_examples.py -> repo root is four parents up.
_REPO_ROOT = Path(__file__).resolve().parents[4]
_LATEX_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "compiler-examples.tex"

_LATEX_HEADER = (
    "% Generated by co_lambda_examples._examples (co-lambda-defun-examples). Do not edit;\n"
    "% regenerate with: python -m co_lambda_examples._examples\n"
)

# Whole-term examples: each closed term is defunctionalized to a module of @interned closure classes.
# Each pairs (title, builder, latex); latex is None to auto-render the term with readable names.
_EXAMPLES: "tuple[tuple[str, Builder, str | None], ...]" = (
    ("Identity", IDENTITY, None),
    ("The constant combinator $K$", KESTREL, None),
    ("Church numeral $2$", church(2), None),
    ("Successor", SUCC, None),
    ("Addition", PLUS, None),
    ("Multiplication", MULT, None),
    ("Zero test", IS_ZERO, None),
    ("Self-application", SELF_APPLY, None),
)


def _listing(source: str) -> str:
    return "\\begin{lstlisting}\n" + source + "\n\\end{lstlisting}\n"


def _example_block(title: str, builder: Builder, latex: "str | None") -> str:
    node = build(builder)
    source = defunctionalize(node)
    rendered = latex if latex is not None else term_to_latex(node)
    heading = f"\\medskip\\noindent\\textbf{{{title}.}}\\quad ${rendered}$\n"
    return heading + _listing(source)


def compiler_examples_fragment() -> str:
    """The committed LaTeX fragment: each example term and the defunctionalized module it compiles to."""
    blocks = [_example_block(title, builder, latex) for title, builder, latex in _EXAMPLES]
    return _LATEX_HEADER + "\n" + "\n".join(blocks)


def main() -> None:
    _LATEX_OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _LATEX_OUTPUT.write_text(compiler_examples_fragment())
    print(f"wrote {_LATEX_OUTPUT}")


if __name__ == "__main__":
    main()
