"""Generate the Omega figure for the paper from the real interpreter.

The figure in the unproductive case study is the graph the solver returns for ``Omega``: a single state
whose head reduction returns to itself, decided as bottom. ``_omega.solve_omega`` checks both facts off the
implementation (the self-contraction and the bottom verdict) before this draws them, so the picture cannot
drift from what the interpreter does. The paper floats and captions the picture; this module owns its body.

``co-lambda-omega-figure`` (``python -m co_lambda_examples._omega_figure``) rewrites the committed
``papers/co-lambda/generated/omega-graph.tex``.
"""

from __future__ import annotations

from pathlib import Path

from co_lambda_examples._omega import solve_omega

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "omega-graph.tex"


def render_tikz() -> str:
    """The ``tikzpicture`` body: the single Omega state, a self-loop for the head reduction that returns to
    it, and the bottom verdict the re-entry forces."""
    lines = [
        "% Generated by co_lambda_examples._omega_figure (co-lambda-omega-figure). Do not edit;",
        "% regenerate with: python -m co_lambda_examples._omega_figure",
        "% The single state, the self-contraction, and the bottom verdict are checked against the interpreter.",
        "\\begin{tikzpicture}[",
        "  font=\\footnotesize,",
        "  state/.style={draw=red!65, fill=red!10, rounded corners, minimum width=12mm, minimum height=8mm, align=center, inner sep=2pt},",
        "  back/.style={-Stealth, red!65, shorten >=1pt, shorten <=1pt},",
        "]",
        "  \\node[state] (omega) at (0,0) {$\\Omega$};",
        "  \\draw[back] (omega) to[out=40,in=-40,looseness=8] node[right]{\\itshape $\\beta$} (omega);",
        "  \\node[anchor=north, align=center] at (0,-1.3) "
        "{\\footnotesize re-enters on the stack, no layer exposed $\\;\\Longrightarrow\\;$ $\\bot$};",
        "\\end{tikzpicture}",
    ]
    return "\n".join(lines) + "\n"


def main() -> None:
    solve_omega()
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(render_tikz())
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
