"""Generate the Omega code listing for the paper, rendered from the HOAS source terms.

The appendix lists the pure-lambda term ``Omega = omega omega`` and the self-application ``omega`` it is
built from. None of it is transcribed by hand: each definition is rendered from the actual ``Builder`` by
``co_lambda._hoas_latex``, with ``omega`` shown by name inside ``Omega`` so the second line reads as the
first applied to itself. Each definition is a ``breqn`` ``dmath*``; the output is written to
``papers/co-lambda/generated/omega-code.tex`` and ``\\input`` by the paper.

``co-lambda-omega-code`` (``python -m co_lambda_examples._omega_code``) rewrites it.
"""

from __future__ import annotations

from dataclasses import replace
from pathlib import Path

from co_lambda._hoas_latex import render
from co_lambda._prelude import SELF_APPLY

from co_lambda_examples._editdistance_code import _BREQN_STYLE
from co_lambda_examples._omega import OMEGA_BUILDER

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "papers" / "co-lambda" / "generated" / "omega-code.tex"

# A pass-through constant style, so a name in the ``names`` map is emitted as raw LaTeX (``\omega``) rather
# than wrapped in ``\mathtt`` (the default for multi-character names), letting the Greek render.
_OMEGA_STYLE = replace(_BREQN_STYLE, constant=lambda name: name)

_LATEX_HEADER = (
    "% Generated by co_lambda_examples._omega_code (co-lambda-omega-code). Do not edit;\n"
    "% regenerate with: python -m co_lambda_examples._omega_code\n"
)


def code_listing() -> str:
    """The committed LaTeX fragment: ``omega`` rendered from its term, then ``Omega`` as ``omega omega``."""
    names = {id(SELF_APPLY): r"\omega"}
    omega_body = render(SELF_APPLY, {}, _OMEGA_STYLE)
    omega_term = render(OMEGA_BUILDER, names, _OMEGA_STYLE)
    parts = [
        _LATEX_HEADER,
        "\\smallskip\\noindent\\textit{self-application}\\par\\nobreak",
        f"\\begin{{dmath*}}\n\\omega = {omega_body}\n\\end{{dmath*}}",
        "\\smallskip\\noindent\\textit{the divergent term}\\par\\nobreak",
        f"\\begin{{dmath*}}\n\\Omega = {omega_term}\n\\end{{dmath*}}",
    ]
    return "\n".join(parts) + "\n"


def main() -> None:
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(code_listing())
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
