"""Committed pre-compiled defunctionalized artifacts: the example apps and inputs the benchmark imports.

The benchmark must run compiled programs WITHOUT compiling anything in the same process (so the
compilation never contends with the measured run). Every compiled application and every compiled input
it needs is therefore defunctionalized ahead of time and committed under ``_generated`` as a
self-contained module exposing ``compiled``; the benchmark merely imports and applies them.

The bootstrap compiler artifact (``compiler`` = DEFUN self-compiled) lives in
``tablambda._generated`` and is regenerated by ``tablambda-regen-compiler``
(``python -m tablambda._compiler_artifact``). This module handles the remaining artifacts:

* apps: ``editdistance`` = the Levenshtein function ``EDIT_DISTANCE``.
* edit-distance inputs: the strings as Scott lists of BinNat character codes (``ord`` codes, so any two
  strings share an encoding and equal characters compare equal).
* DEFUN inputs: the quoted source programs ``quote(P)`` the compiler consumes (``identity``, ``S``, and
  ``DEFUN`` itself -- the bootstrap input).

Values are built lazily (callables) so importing this module is cheap; ``DEFUN`` and its quotation are
deep, so they are realized only during generation, under a raised recursion limit. ``main`` (also
``python -m tablambda_examples._artifacts [name ...]``) regenerates the committed modules for the running
Python version; generation is heavy (the ``input_quote_defun`` artifact takes minutes).
"""

from __future__ import annotations

import sys

from pathlib import Path
from typing import Callable

from tablambda._codec import int_to_binnat, quote_binnat
from tablambda._defun_codegen import DEFUN
from tablambda._dsl import Builder, app, build, lam
from tablambda._prelude import IDENTITY, SCOTT_NIL
from tablambda._sugar import cons

from tablambda_examples._editdistance import EDIT_DISTANCE

_GENERATED_DIR = Path(__file__).resolve().parent / "_generated"


def _string_term(text: str) -> Builder:
    """A string as a Scott list of BinNat ``ord`` character codes."""
    result: Builder = SCOTT_NIL
    for character in reversed(text):
        result = cons(int_to_binnat(ord(character)), result)
    return result


def _quote_term(builder: Builder) -> Builder:
    """The BinNat-quoted form ``quote_binnat(P)`` of a program, as a Builder (built under a raised
    recursion limit). The defunctionalization compiler consumes BinNat-quoted terms."""
    return quote_binnat(build(builder))


_S_COMBINATOR: Builder = lam(lambda x: lam(lambda y: lam(lambda z: app(app(x, z), app(y, z)))))


# name -> a thunk producing the Builder to defunctionalize (lazy, so importing this module never builds
# the deep DEFUN term). The committed module is ``_generated_defun_<name>_<pytag>.py``.
ARTIFACTS: "dict[str, Callable[[], Builder]]" = {
    "editdistance": lambda: EDIT_DISTANCE,
    "input_kitten": lambda: _string_term("kitten"),
    "input_sitting": lambda: _string_term("sitting"),
    "input_intention": lambda: _string_term("intention"),
    "input_execution": lambda: _string_term("execution"),
    "input_quote_identity": lambda: _quote_term(IDENTITY),
    "input_quote_s": lambda: _quote_term(_S_COMBINATOR),
    "input_quote_defun": lambda: _quote_term(DEFUN),
}


# Artifacts whose generation recurses deeper than Python 3.12+'s fixed C-recursion cap allows (the cap
# is not liftable by ``setrecursionlimit`` or a larger thread stack). Only the pre-3.12 recursion model
# can build them; they power the (consequently 3.11-only) bootstrap benchmark cell. The cap is hit by
# the fixpoints property-access descent, not plain recursion or ast.unparse; see the trampoline TODO in
# fixpoints._core.fixpoint_cached_property for the fix that would make these buildable on 3.12+.
_DEEP_ARTIFACTS = frozenset({"input_quote_defun"})


def feasible_artifacts() -> "list[str]":
    """The artifact names buildable on the running Python (excludes deep ones on 3.12+)."""
    if sys.version_info >= (3, 12):
        return [name for name in ARTIFACTS if name not in _DEEP_ARTIFACTS]
    return list(ARTIFACTS)


def module_basename(name: str) -> str:
    """The committed module file stem for an artifact under the running Python version."""
    from tablambda._defun_runtime import _python_tag

    return f"_generated_defun_{name}_{_python_tag()}"


def module_dotted_name(name: str) -> str:
    """The importable dotted module name for an artifact.

    The ``compiler`` artifact lives in ``tablambda._generated``; all others live here under
    ``tablambda_examples._generated``.
    """
    if name == "compiler":
        from tablambda._compiler_artifact import module_dotted_name as _compiler_dotted_name

        return _compiler_dotted_name()
    return f"tablambda_examples._generated.{module_basename(name)}"


def generate(name: str) -> Path:
    """Defunctionalize one artifact and write its committed module for the running Python version.

    Building deep terms (``quote(DEFUN)``) and defunctionalizing them recurse as deep as the term, which
    overflows the C stack on Python 3.12+; both run in a large-stack thread.
    """
    from tablambda._defunctionalize import defunctionalize, runnable_defun_module
    from tablambda._defun_runtime import run_in_large_stack

    node = run_in_large_stack(lambda: build(ARTIFACTS[name]()))
    source = runnable_defun_module(defunctionalize(node))
    path = _GENERATED_DIR / f"{module_basename(name)}.py"
    path.write_text(source)
    return path


def main() -> None:
    """Regenerate the named artifacts (default: all feasible) for the running Python version."""
    names = sys.argv[1:] or feasible_artifacts()
    for name in names:
        path = generate(name)
        print(f"wrote {path.name} ({path.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
