"""Generate the edit-distance code listing for the paper, rendered from the HOAS source terms.

The appendix lists the pure-lambda library the edit-distance term is built from: the fixed-point
combinator, the Scott booleans and lists, the binary-natural arithmetic the costs use, and the term
itself. None of it is transcribed by hand. Each definition is the actual ``Builder`` from the source,
rendered by ``tablambda._hoas_latex`` with the bound-variable names the Python lambdas carry and with the
other library constants shown by name (recognised by object identity), so a definition reads as itself and
cross-references the rest. Each definition is wrapped in ``align*`` + ``autobreak`` so the long terms wrap
automatically; the output is written to ``paper/generated/editdistance-code.tex`` and ``\\input`` by the paper.

``tablambda-editdistance-code`` (``python -m tablambda_examples._editdistance_code``) rewrites it.
"""

from __future__ import annotations

from pathlib import Path

from tablambda import _binnat as binnat
from tablambda._dsl import Builder
from tablambda._hoas_latex import MATH_STYLE, Style, render
from tablambda._prelude import AND, FALSE, OR, SCOTT_CONS, SCOTT_NIL, TRUE, Y

from tablambda_examples._editdistance import EDIT_DISTANCE, LENGTH

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "paper" / "generated" / "editdistance-code.tex"

# (group heading, ((name, builder), ...)). Order is dependency order: a definition uses only names above
# it. ``zero`` is ``nil`` (the BinNat 0 is the empty list of bits), the same term, so it is not relisted.
_GROUPS: "tuple[tuple[str, tuple[tuple[str, Builder], ...]], ...]" = (
    ("fixed point", (("Y", Y),)),
    ("Scott booleans", (("true", TRUE), ("false", FALSE), ("and", AND), ("or", OR))),
    ("Scott lists (nil is also the BinNat zero)", (("nil", SCOTT_NIL), ("cons", SCOTT_CONS))),
    ("comparison verdicts (a verdict picks one of less, equal, greater)", (
        ("less", binnat._LESS), ("equal", binnat._EQUAL), ("greater", binnat._GREATER),
    )),
    ("BinNat bit operations", (
        ("one", binnat.BIN_ONE),
        ("not", binnat._not),
        ("xor", binnat._xor),
        ("maj", binnat._majority),
        ("biteq", binnat._bit_equal),
        ("bitcmp", binnat._bit_compare),
    )),
    ("BinNat arithmetic and comparison", (
        ("iszero", binnat.BIN_IS_ZERO),
        ("addc", binnat._ADD_CARRY),
        ("add", binnat.BIN_ADD),
        ("succ", binnat.BIN_SUCC),
        ("cmp", binnat.BIN_CMP),
        ("eq", binnat.BIN_EQUAL),
        ("min", binnat.BIN_MIN),
    )),
    ("edit distance", (("len", LENGTH), ("ed", EDIT_DISTANCE))),
)

_LATEX_HEADER = (
    "% Generated by tablambda_examples._editdistance_code (tablambda-editdistance-code). Do not edit;\n"
    "% regenerate with: python -m tablambda_examples._editdistance_code\n"
)

# An autobreak-friendly variant of the math style: a source newline after every application space and
# lambda dot. autobreak breaks at source line ends, so these newlines are where it wraps the
# application-heavy terms (which carry no binary operator for it to break at on its own).
_AUTOBREAK_STYLE: Style = Style(
    constant=MATH_STYLE.constant,
    binder=MATH_STYLE.binder,
    abstraction=lambda binder, body: f"\\lambda {binder}.\\,\n{body}",
    application=lambda function, argument: f"{function}\\,\n{argument}",
    parenthesise=MATH_STYLE.parenthesise,
)


def _names() -> "dict[int, str]":
    names: "dict[int, str]" = {}
    for _heading, definitions in _GROUPS:
        for name, builder in definitions:
            names.setdefault(id(builder), name)
    return names


def code_listing() -> str:
    """The committed LaTeX fragment: each definition in ``align*`` + ``autobreak``, rendered from its HOAS term."""
    names = _names()
    parts = [_LATEX_HEADER]
    for heading, definitions in _GROUPS:
        parts.append(f"\\smallskip\\noindent\\textit{{{heading}}}\\par\\nobreak")
        for name, builder in definitions:
            left = MATH_STYLE.constant(name)
            right = render(builder, names, _AUTOBREAK_STYLE)
            parts.append(f"\\begin{{align*}}\n\\begin{{autobreak}}\n{left} = {right}\n\\end{{autobreak}}\n\\end{{align*}}")
    return "\n".join(parts) + "\n"


def main() -> None:
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(code_listing())
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
