"""Write the generated DEFUN compiler-example LaTeX fragment.

The console entry point ``tablambda-defun-examples`` (see ``pyproject.toml``) runs ``main``;
equivalently ``python -m tablambda_examples._examples``. The output is committed under
``paper/generated/`` and ``\\input`` by the paper; a test asserts the committed file matches
this builder, so regenerating after a compiler change is mandatory (and idempotent otherwise). Every
example runs the real DEFUN compiler: a term is ``defunctionalize`` of the term, the module of
``@interned`` closure classes it compiles to (one class per distinct source ``Lam``, each class's
``__call__`` the compiled beta reduction, applications emitted as ``Thunk`` nodes). The displayed
lambda is ``term_to_latex`` of the term (readable names).
"""

from __future__ import annotations

import os

from pathlib import Path

from tablambda._codec import church
from tablambda._defunctionalize import defunctionalize
from tablambda._dsl import Builder, app, build, lam
from tablambda._latex import term_to_latex
from tablambda._prelude import IDENTITY, IS_ZERO, KESTREL, MULT, PLUS, SELF_APPLY, SUCC

# lambda a. (lambda v. a) (lambda b. lambda v. a): the two inner abstractions have the same
# body shape and capture the same a, but at binding depths one apart, so their de Bruijn
# terms are distinct interned nodes while their compiled classes coincide by content address.
DEPTH_CAPTURES: Builder = lam(
    lambda a: app(lam(lambda v: a), lam(lambda b: lam(lambda v: a)))
)

# src/tablambda_examples/_examples.py -> repo root is four parents up.
_REPO_ROOT = Path(__file__).resolve().parents[4]


def _latex_output() -> Path:
    """Where this interpreter's fragment is written: ``compiler-examples-<tag>.tex`` in the
    generated dir, the tag naming the Python version whose ``ast.unparse`` output it is.

    The directory is ``$TABLAMBDA_GENERATED_DIR`` when set (so a read-only Nix-store venv can
    target the working tree), else ``paper/generated`` beside the editable source. Only the
    py311 fragment is committed and input by the paper.
    """
    from tablambda._defun_runtime import _python_tag

    override = os.environ.get("TABLAMBDA_GENERATED_DIR")
    directory = Path(override) if override else _REPO_ROOT / "paper" / "generated"
    return directory / f"compiler-examples-{_python_tag()}.tex"

_LATEX_HEADER = (
    "% Generated by tablambda_examples._examples (tablambda-defun-examples). Do not edit;\n"
    "% regenerate with: python -m tablambda_examples._examples\n"
)

# Whole-term examples: each closed term is defunctionalized to a module of @interned closure classes.
# Each pairs (title, builder, latex); latex is None to auto-render the term with readable names.
_EXAMPLES: "tuple[tuple[str, Builder, str | None], ...]" = (
    ("Identity", IDENTITY, None),
    ("The constant combinator $K$", KESTREL, None),
    ("Church numeral $2$", church(2), None),
    ("Successor", SUCC, None),
    ("Addition", PLUS, None),
    ("Multiplication", MULT, None),
    ("Zero test", IS_ZERO, None),
    ("Self-application", SELF_APPLY, None),
    # Two inner abstractions with the same body shape capturing the same variable at
    # different binding depths: distinct de Bruijn terms, one content-addressed class.
    ("Depth-differing captures", DEPTH_CAPTURES, None),
)


def _listing(source: str) -> str:
    return "\\begin{lstlisting}\n" + source + "\n\\end{lstlisting}\n"


def _example_block(title: str, builder: Builder, latex: "str | None") -> str:
    node = build(builder)
    source = defunctionalize(node)
    rendered = latex if latex is not None else term_to_latex(node)
    heading = f"\\medskip\\noindent\\textbf{{{title}.}}\\quad ${rendered}$\n"
    return heading + _listing(source)


def compiler_examples_fragment() -> str:
    """The committed LaTeX fragment: each example term and the defunctionalized module it compiles to."""
    blocks = [_example_block(title, builder, latex) for title, builder, latex in _EXAMPLES]
    return _LATEX_HEADER + "\n" + "\n".join(blocks)


def main() -> None:
    output = _latex_output()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(compiler_examples_fragment())
    print(f"wrote {output}")


if __name__ == "__main__":
    main()
