"""Generate the step-by-step Omega trace, Omega decided as bottom.

The case study's claim is that the solver stops on ``Omega`` where ordinary reduction loops: it contracts
the head redex once, finds the contractum is ``Omega`` itself, re-enters that term while it is still on the
stack with no weak head normal form reached, and returns its running approximation, bottom, which then stabilizes. We do not
assert that in prose, we read it off the implementation: ``_omega.solve_omega`` checks the self-contraction
(an interning identity) and the bottom verdict before the trace is rendered. The listing shows the step
sequence so the re-entry that forces bottom in finite time is visible. The output goes to
``paper/generated/omega-trace.tex``, ``\\input`` by the paper.

``tablambda-omega-trace`` (``python -m tablambda_examples._omega_trace``) rewrites it.
"""

from __future__ import annotations

from pathlib import Path

from tablambda_examples._omega import trace_lines

_REPO_ROOT = Path(__file__).resolve().parents[4]
_OUTPUT = _REPO_ROOT / "paper" / "generated" / "omega-trace.tex"


def render_trace() -> str:
    """The committed LaTeX fragment: the term-level run of ``TabledWHNF`` on ``Omega``, generated from the real
    terms (the head reduction back to ``Omega``, the stack re-entry with no weak head normal form reached, and bottom)."""
    header = (
        "% Generated by tablambda_examples._omega_trace (tablambda-omega-trace). Do not edit;\n"
        "% regenerate with: python -m tablambda_examples._omega_trace\n"
    )
    listing = "\\begin{lstlisting}[language=]\n" + "\n".join(trace_lines()) + "\n\\end{lstlisting}\n"
    return header + "\n" + listing


def main() -> None:
    _OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT.write_text(render_trace())
    print(f"wrote {_OUTPUT}")


if __name__ == "__main__":
    main()
